disabled_rules:
    - trailing_whitespace
    - identifier_name
    - line_length
    - type_name
    - legacy_constructor
    - unused_setter_value
    - void_function_in_ternary
    - function_parameter_count
    - function_body_length
    - nesting
    - comment_spacing
    - cyclomatic_complexity
 
opt_in_rules:
    - empty_count
    - empty_string
    - closure_end_indentation
    - let_var_whitespace
 
